url    : "https://intellify-cloud.github.io/olink/"
baseurl: ""

title      : oobalink
email      : info@oobalink.co.za
description: "Go online. Grow online."
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD